"""empty message

Revision ID: 912e2d607153
Revises: 6a1a17236ec1
Create Date: 2025-05-11 15:11:27.621011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912e2d607153'
down_revision = '6a1a17236ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('t_user', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'update_time')
    op.drop_column('t_user', 'create_time')
    # ### end Alembic commands ###
